// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Workstation.ServiceModel.Ua
{
    using System.Collections.Generic;

    public static class StatusCodes
    {
        /// <summary>The result was successful.</summary>
        public const uint Good = 0x00000000u;
        /// <summary>An unexpected error occurred.</summary>
        public const uint BadUnexpectedError = 0x80010000u;
        /// <summary>An internal error occurred as a result of a programming or configuration error.</summary>
        public const uint BadInternalError = 0x80020000u;
        /// <summary>Not enough memory to complete the operation.</summary>
        public const uint BadOutOfMemory = 0x80030000u;
        /// <summary>An operating system resource is not available.</summary>
        public const uint BadResourceUnavailable = 0x80040000u;
        /// <summary>A low level communication error occurred.</summary>
        public const uint BadCommunicationError = 0x80050000u;
        /// <summary>Encoding halted because of invalid data in the objects being serialized.</summary>
        public const uint BadEncodingError = 0x80060000u;
        /// <summary>Decoding halted because of invalid data in the stream.</summary>
        public const uint BadDecodingError = 0x80070000u;
        /// <summary>The message encoding/decoding limits imposed by the stack have been exceeded.</summary>
        public const uint BadEncodingLimitsExceeded = 0x80080000u;
        /// <summary>The request message size exceeds limits set by the server.</summary>
        public const uint BadRequestTooLarge = 0x80B80000u;
        /// <summary>The response message size exceeds limits set by the client.</summary>
        public const uint BadResponseTooLarge = 0x80B90000u;
        /// <summary>An unrecognized response was received from the server.</summary>
        public const uint BadUnknownResponse = 0x80090000u;
        /// <summary>The operation timed out.</summary>
        public const uint BadTimeout = 0x800A0000u;
        /// <summary>The server does not support the requested service.</summary>
        public const uint BadServiceUnsupported = 0x800B0000u;
        /// <summary>The operation was cancelled because the application is shutting down.</summary>
        public const uint BadShutdown = 0x800C0000u;
        /// <summary>The operation could not complete because the client is not connected to the server.</summary>
        public const uint BadServerNotConnected = 0x800D0000u;
        /// <summary>The server has stopped and cannot process any requests.</summary>
        public const uint BadServerHalted = 0x800E0000u;
        /// <summary>There was nothing to do because the client passed a list of operations with no elements.</summary>
        public const uint BadNothingToDo = 0x800F0000u;
        /// <summary>The request could not be processed because it specified too many operations.</summary>
        public const uint BadTooManyOperations = 0x80100000u;
        /// <summary>The request could not be processed because there are too many monitored items in the subscription.</summary>
        public const uint BadTooManyMonitoredItems = 0x80DB0000u;
        /// <summary>The extension object cannot be (de)serialized because the data type id is not recognized.</summary>
        public const uint BadDataTypeIdUnknown = 0x80110000u;
        /// <summary>The certificate provided as a parameter is not valid.</summary>
        public const uint BadCertificateInvalid = 0x80120000u;
        /// <summary>An error occurred verifying security.</summary>
        public const uint BadSecurityChecksFailed = 0x80130000u;
        /// <summary>The certificate does not meet the requirements of the security policy.</summary>
        public const uint BadCertificatePolicyCheckFailed = 0x81140000u;
        /// <summary>The certificate has expired or is not yet valid.</summary>
        public const uint BadCertificateTimeInvalid = 0x80140000u;
        /// <summary>An issuer certificate has expired or is not yet valid.</summary>
        public const uint BadCertificateIssuerTimeInvalid = 0x80150000u;
        /// <summary>The HostName used to connect to a server does not match a HostName in the certificate.</summary>
        public const uint BadCertificateHostNameInvalid = 0x80160000u;
        /// <summary>The URI specified in the ApplicationDescription does not match the URI in the certificate.</summary>
        public const uint BadCertificateUriInvalid = 0x80170000u;
        /// <summary>The certificate may not be used for the requested operation.</summary>
        public const uint BadCertificateUseNotAllowed = 0x80180000u;
        /// <summary>The issuer certificate may not be used for the requested operation.</summary>
        public const uint BadCertificateIssuerUseNotAllowed = 0x80190000u;
        /// <summary>The certificate is not trusted.</summary>
        public const uint BadCertificateUntrusted = 0x801A0000u;
        /// <summary>It was not possible to determine if the certificate has been revoked.</summary>
        public const uint BadCertificateRevocationUnknown = 0x801B0000u;
        /// <summary>It was not possible to determine if the issuer certificate has been revoked.</summary>
        public const uint BadCertificateIssuerRevocationUnknown = 0x801C0000u;
        /// <summary>The certificate has been revoked.</summary>
        public const uint BadCertificateRevoked = 0x801D0000u;
        /// <summary>The issuer certificate has been revoked.</summary>
        public const uint BadCertificateIssuerRevoked = 0x801E0000u;
        /// <summary>The certificate chain is incomplete.</summary>
        public const uint BadCertificateChainIncomplete = 0x810D0000u;
        /// <summary>User does not have permission to perform the requested operation.</summary>
        public const uint BadUserAccessDenied = 0x801F0000u;
        /// <summary>The user identity token is not valid.</summary>
        public const uint BadIdentityTokenInvalid = 0x80200000u;
        /// <summary>The user identity token is valid but the server has rejected it.</summary>
        public const uint BadIdentityTokenRejected = 0x80210000u;
        /// <summary>The specified secure channel is no longer valid.</summary>
        public const uint BadSecureChannelIdInvalid = 0x80220000u;
        /// <summary>The timestamp is outside the range allowed by the server.</summary>
        public const uint BadInvalidTimestamp = 0x80230000u;
        /// <summary>The nonce does appear to be not a random value or it is not the correct length.</summary>
        public const uint BadNonceInvalid = 0x80240000u;
        /// <summary>The session id is not valid.</summary>
        public const uint BadSessionIdInvalid = 0x80250000u;
        /// <summary>The session was closed by the client.</summary>
        public const uint BadSessionClosed = 0x80260000u;
        /// <summary>The session cannot be used because ActivateSession has not been called.</summary>
        public const uint BadSessionNotActivated = 0x80270000u;
        /// <summary>The subscription id is not valid.</summary>
        public const uint BadSubscriptionIdInvalid = 0x80280000u;
        /// <summary>The header for the request is missing or invalid.</summary>
        public const uint BadRequestHeaderInvalid = 0x802A0000u;
        /// <summary>The timestamps to return parameter is invalid.</summary>
        public const uint BadTimestampsToReturnInvalid = 0x802B0000u;
        /// <summary>The request was cancelled by the client.</summary>
        public const uint BadRequestCancelledByClient = 0x802C0000u;
        /// <summary>Too many arguments were provided.</summary>
        public const uint BadTooManyArguments = 0x80E50000u;
        /// <summary>The server requires a license to operate in general or to perform a service or operation, but existing license is expired.</summary>
        public const uint BadLicenseExpired = 0x810E0000u;
        /// <summary>The server has limits on number of allowed operations / objects, based on installed licenses, and these limits where exceeded.</summary>
        public const uint BadLicenseLimitsExceeded = 0x810F0000u;
        /// <summary>The server does not have a license which is required to operate in general or to perform a service or operation.</summary>
        public const uint BadLicenseNotAvailable = 0x81100000u;
        /// <summary>The subscription was transferred to another session.</summary>
        public const uint GoodSubscriptionTransferred = 0x002D0000u;
        /// <summary>The processing will complete asynchronously.</summary>
        public const uint GoodCompletesAsynchronously = 0x002E0000u;
        /// <summary>Sampling has slowed down due to resource limitations.</summary>
        public const uint GoodOverload = 0x002F0000u;
        /// <summary>The value written was accepted but was clamped.</summary>
        public const uint GoodClamped = 0x00300000u;
        /// <summary>Communication with the data source is defined, but not established, and there is no last known value available.</summary>
        public const uint BadNoCommunication = 0x80310000u;
        /// <summary>Waiting for the server to obtain values from the underlying data source.</summary>
        public const uint BadWaitingForInitialData = 0x80320000u;
        /// <summary>The syntax of the node id is not valid.</summary>
        public const uint BadNodeIdInvalid = 0x80330000u;
        /// <summary>The node id refers to a node that does not exist in the server address space.</summary>
        public const uint BadNodeIdUnknown = 0x80340000u;
        /// <summary>The attribute is not supported for the specified Node.</summary>
        public const uint BadAttributeIdInvalid = 0x80350000u;
        /// <summary>The syntax of the index range parameter is invalid.</summary>
        public const uint BadIndexRangeInvalid = 0x80360000u;
        /// <summary>No data exists within the range of indexes specified.</summary>
        public const uint BadIndexRangeNoData = 0x80370000u;
        /// <summary>The data encoding is invalid.</summary>
        public const uint BadDataEncodingInvalid = 0x80380000u;
        /// <summary>The server does not support the requested data encoding for the node.</summary>
        public const uint BadDataEncodingUnsupported = 0x80390000u;
        /// <summary>The access level does not allow reading or subscribing to the Node.</summary>
        public const uint BadNotReadable = 0x803A0000u;
        /// <summary>The access level does not allow writing to the Node.</summary>
        public const uint BadNotWritable = 0x803B0000u;
        /// <summary>The value was out of range.</summary>
        public const uint BadOutOfRange = 0x803C0000u;
        /// <summary>The requested operation is not supported.</summary>
        public const uint BadNotSupported = 0x803D0000u;
        /// <summary>A requested item was not found or a search operation ended without success.</summary>
        public const uint BadNotFound = 0x803E0000u;
        /// <summary>The object cannot be used because it has been deleted.</summary>
        public const uint BadObjectDeleted = 0x803F0000u;
        /// <summary>Requested operation is not implemented.</summary>
        public const uint BadNotImplemented = 0x80400000u;
        /// <summary>The monitoring mode is invalid.</summary>
        public const uint BadMonitoringModeInvalid = 0x80410000u;
        /// <summary>The monitoring item id does not refer to a valid monitored item.</summary>
        public const uint BadMonitoredItemIdInvalid = 0x80420000u;
        /// <summary>The monitored item filter parameter is not valid.</summary>
        public const uint BadMonitoredItemFilterInvalid = 0x80430000u;
        /// <summary>The server does not support the requested monitored item filter.</summary>
        public const uint BadMonitoredItemFilterUnsupported = 0x80440000u;
        /// <summary>A monitoring filter cannot be used in combination with the attribute specified.</summary>
        public const uint BadFilterNotAllowed = 0x80450000u;
        /// <summary>A mandatory structured parameter was missing or null.</summary>
        public const uint BadStructureMissing = 0x80460000u;
        /// <summary>The event filter is not valid.</summary>
        public const uint BadEventFilterInvalid = 0x80470000u;
        /// <summary>The content filter is not valid.</summary>
        public const uint BadContentFilterInvalid = 0x80480000u;
        /// <summary>An unrecognized operator was provided in a filter.</summary>
        public const uint BadFilterOperatorInvalid = 0x80C10000u;
        /// <summary>A valid operator was provided, but the server does not provide support for this filter operator.</summary>
        public const uint BadFilterOperatorUnsupported = 0x80C20000u;
        /// <summary>The number of operands provided for the filter operator was less then expected for the operand provided.</summary>
        public const uint BadFilterOperandCountMismatch = 0x80C30000u;
        /// <summary>The operand used in a content filter is not valid.</summary>
        public const uint BadFilterOperandInvalid = 0x80490000u;
        /// <summary>The referenced element is not a valid element in the content filter.</summary>
        public const uint BadFilterElementInvalid = 0x80C40000u;
        /// <summary>The referenced literal is not a valid value.</summary>
        public const uint BadFilterLiteralInvalid = 0x80C50000u;
        /// <summary>The continuation point provide is longer valid.</summary>
        public const uint BadContinuationPointInvalid = 0x804A0000u;
        /// <summary>The operation could not be processed because all continuation points have been allocated.</summary>
        public const uint BadNoContinuationPoints = 0x804B0000u;
        /// <summary>The reference type id does not refer to a valid reference type node.</summary>
        public const uint BadReferenceTypeIdInvalid = 0x804C0000u;
        /// <summary>The browse direction is not valid.</summary>
        public const uint BadBrowseDirectionInvalid = 0x804D0000u;
        /// <summary>The node is not part of the view.</summary>
        public const uint BadNodeNotInView = 0x804E0000u;
        /// <summary>The number was not accepted because of a numeric overflow.</summary>
        public const uint BadNumericOverflow = 0x81120000u;
        /// <summary>The ServerUri is not a valid URI.</summary>
        public const uint BadServerUriInvalid = 0x804F0000u;
        /// <summary>No ServerName was specified.</summary>
        public const uint BadServerNameMissing = 0x80500000u;
        /// <summary>No DiscoveryUrl was specified.</summary>
        public const uint BadDiscoveryUrlMissing = 0x80510000u;
        /// <summary>The semaphore file specified by the client is not valid.</summary>
        public const uint BadSempahoreFileMissing = 0x80520000u;
        /// <summary>The security token request type is not valid.</summary>
        public const uint BadRequestTypeInvalid = 0x80530000u;
        /// <summary>The security mode does not meet the requirements set by the server.</summary>
        public const uint BadSecurityModeRejected = 0x80540000u;
        /// <summary>The security policy does not meet the requirements set by the server.</summary>
        public const uint BadSecurityPolicyRejected = 0x80550000u;
        /// <summary>The server has reached its maximum number of sessions.</summary>
        public const uint BadTooManySessions = 0x80560000u;
        /// <summary>The user token signature is missing or invalid.</summary>
        public const uint BadUserSignatureInvalid = 0x80570000u;
        /// <summary>The signature generated with the client certificate is missing or invalid.</summary>
        public const uint BadApplicationSignatureInvalid = 0x80580000u;
        /// <summary>The client did not provide at least one software certificate that is valid and meets the profile requirements for the server.</summary>
        public const uint BadNoValidCertificates = 0x80590000u;
        /// <summary>The server does not support changing the user identity assigned to the session.</summary>
        public const uint BadIdentityChangeNotSupported = 0x80C60000u;
        /// <summary>The request was cancelled by the client with the Cancel service.</summary>
        public const uint BadRequestCancelledByRequest = 0x805A0000u;
        /// <summary>The parent node id does not to refer to a valid node.</summary>
        public const uint BadParentNodeIdInvalid = 0x805B0000u;
        /// <summary>The reference could not be created because it violates constraints imposed by the data model.</summary>
        public const uint BadReferenceNotAllowed = 0x805C0000u;
        /// <summary>The requested node id was reject because it was either invalid or server does not allow node ids to be specified by the client.</summary>
        public const uint BadNodeIdRejected = 0x805D0000u;
        /// <summary>The requested node id is already used by another node.</summary>
        public const uint BadNodeIdExists = 0x805E0000u;
        /// <summary>The node class is not valid.</summary>
        public const uint BadNodeClassInvalid = 0x805F0000u;
        /// <summary>The browse name is invalid.</summary>
        public const uint BadBrowseNameInvalid = 0x80600000u;
        /// <summary>The browse name is not unique among nodes that share the same relationship with the parent.</summary>
        public const uint BadBrowseNameDuplicated = 0x80610000u;
        /// <summary>The node attributes are not valid for the node class.</summary>
        public const uint BadNodeAttributesInvalid = 0x80620000u;
        /// <summary>The type definition node id does not reference an appropriate type node.</summary>
        public const uint BadTypeDefinitionInvalid = 0x80630000u;
        /// <summary>The source node id does not reference a valid node.</summary>
        public const uint BadSourceNodeIdInvalid = 0x80640000u;
        /// <summary>The target node id does not reference a valid node.</summary>
        public const uint BadTargetNodeIdInvalid = 0x80650000u;
        /// <summary>The reference type between the nodes is already defined.</summary>
        public const uint BadDuplicateReferenceNotAllowed = 0x80660000u;
        /// <summary>The server does not allow this type of self reference on this node.</summary>
        public const uint BadInvalidSelfReference = 0x80670000u;
        /// <summary>The reference type is not valid for a reference to a remote server.</summary>
        public const uint BadReferenceLocalOnly = 0x80680000u;
        /// <summary>The server will not allow the node to be deleted.</summary>
        public const uint BadNoDeleteRights = 0x80690000u;
        /// <summary>The server was not able to delete all target references.</summary>
        public const uint UncertainReferenceNotDeleted = 0x40BC0000u;
        /// <summary>The server index is not valid.</summary>
        public const uint BadServerIndexInvalid = 0x806A0000u;
        /// <summary>The view id does not refer to a valid view node.</summary>
        public const uint BadViewIdUnknown = 0x806B0000u;
        /// <summary>The view timestamp is not available or not supported.</summary>
        public const uint BadViewTimestampInvalid = 0x80C90000u;
        /// <summary>The view parameters are not consistent with each other.</summary>
        public const uint BadViewParameterMismatch = 0x80CA0000u;
        /// <summary>The view version is not available or not supported.</summary>
        public const uint BadViewVersionInvalid = 0x80CB0000u;
        /// <summary>The list of references may not be complete because the underlying system is not available.</summary>
        public const uint UncertainNotAllNodesAvailable = 0x40C00000u;
        /// <summary>The server should have followed a reference to a node in a remote server but did not. The result set may be incomplete.</summary>
        public const uint GoodResultsMayBeIncomplete = 0x00BA0000u;
        /// <summary>The provided Nodeid was not a type definition nodeid.</summary>
        public const uint BadNotTypeDefinition = 0x80C80000u;
        /// <summary>One of the references to follow in the relative path references to a node in the address space in another server.</summary>
        public const uint UncertainReferenceOutOfServer = 0x406C0000u;
        /// <summary>The requested operation has too many matches to return.</summary>
        public const uint BadTooManyMatches = 0x806D0000u;
        /// <summary>The requested operation requires too many resources in the server.</summary>
        public const uint BadQueryTooComplex = 0x806E0000u;
        /// <summary>The requested operation has no match to return.</summary>
        public const uint BadNoMatch = 0x806F0000u;
        /// <summary>The max age parameter is invalid.</summary>
        public const uint BadMaxAgeInvalid = 0x80700000u;
        /// <summary>The operation is not permitted over the current secure channel.</summary>
        public const uint BadSecurityModeInsufficient = 0x80E60000u;
        /// <summary>The history details parameter is not valid.</summary>
        public const uint BadHistoryOperationInvalid = 0x80710000u;
        /// <summary>The server does not support the requested operation.</summary>
        public const uint BadHistoryOperationUnsupported = 0x80720000u;
        /// <summary>The defined timestamp to return was invalid.</summary>
        public const uint BadInvalidTimestampArgument = 0x80BD0000u;
        /// <summary>The server does not support writing the combination of value, status and timestamps provided.</summary>
        public const uint BadWriteNotSupported = 0x80730000u;
        /// <summary>The value supplied for the attribute is not of the same type as the attribute's value.</summary>
        public const uint BadTypeMismatch = 0x80740000u;
        /// <summary>The method id does not refer to a method for the specified object.</summary>
        public const uint BadMethodInvalid = 0x80750000u;
        /// <summary>The client did not specify all of the input arguments for the method.</summary>
        public const uint BadArgumentsMissing = 0x80760000u;
        /// <summary>The executable attribute does not allow the execution of the method.</summary>
        public const uint BadNotExecutable = 0x81110000u;
        /// <summary>The server has reached its maximum number of subscriptions.</summary>
        public const uint BadTooManySubscriptions = 0x80770000u;
        /// <summary>The server has reached the maximum number of queued publish requests.</summary>
        public const uint BadTooManyPublishRequests = 0x80780000u;
        /// <summary>There is no subscription available for this session.</summary>
        public const uint BadNoSubscription = 0x80790000u;
        /// <summary>The sequence number is unknown to the server.</summary>
        public const uint BadSequenceNumberUnknown = 0x807A0000u;
        /// <summary>The requested notification message is no longer available.</summary>
        public const uint BadMessageNotAvailable = 0x807B0000u;
        /// <summary>The client of the current session does not support one or more Profiles that are necessary for the subscription.</summary>
        public const uint BadInsufficientClientProfile = 0x807C0000u;
        /// <summary>The sub-state machine is not currently active.</summary>
        public const uint BadStateNotActive = 0x80BF0000u;
        /// <summary>An equivalent rule already exists.</summary>
        public const uint BadAlreadyExists = 0x81150000u;
        /// <summary>The server cannot process the request because it is too busy.</summary>
        public const uint BadTcpServerTooBusy = 0x807D0000u;
        /// <summary>The type of the message specified in the header invalid.</summary>
        public const uint BadTcpMessageTypeInvalid = 0x807E0000u;
        /// <summary>The SecureChannelId and/or TokenId are not currently in use.</summary>
        public const uint BadTcpSecureChannelUnknown = 0x807F0000u;
        /// <summary>The size of the message specified in the header is too large.</summary>
        public const uint BadTcpMessageTooLarge = 0x80800000u;
        /// <summary>There are not enough resources to process the request.</summary>
        public const uint BadTcpNotEnoughResources = 0x80810000u;
        /// <summary>An internal error occurred.</summary>
        public const uint BadTcpInternalError = 0x80820000u;
        /// <summary>The server does not recognize the QueryString specified.</summary>
        public const uint BadTcpEndpointUrlInvalid = 0x80830000u;
        /// <summary>The request could not be sent because of a network interruption.</summary>
        public const uint BadRequestInterrupted = 0x80840000u;
        /// <summary>Timeout occurred while processing the request.</summary>
        public const uint BadRequestTimeout = 0x80850000u;
        /// <summary>The secure channel has been closed.</summary>
        public const uint BadSecureChannelClosed = 0x80860000u;
        /// <summary>The token has expired or is not recognized.</summary>
        public const uint BadSecureChannelTokenUnknown = 0x80870000u;
        /// <summary>The sequence number is not valid.</summary>
        public const uint BadSequenceNumberInvalid = 0x80880000u;
        /// <summary>The applications do not have compatible protocol versions.</summary>
        public const uint BadProtocolVersionUnsupported = 0x80BE0000u;
        /// <summary>There is a problem with the configuration that affects the usefulness of the value.</summary>
        public const uint BadConfigurationError = 0x80890000u;
        /// <summary>The variable should receive its value from another variable, but has never been configured to do so.</summary>
        public const uint BadNotConnected = 0x808A0000u;
        /// <summary>There has been a failure in the device/data source that generates the value that has affected the value.</summary>
        public const uint BadDeviceFailure = 0x808B0000u;
        /// <summary>There has been a failure in the sensor from which the value is derived by the device/data source.</summary>
        public const uint BadSensorFailure = 0x808C0000u;
        /// <summary>The source of the data is not operational.</summary>
        public const uint BadOutOfService = 0x808D0000u;
        /// <summary>The deadband filter is not valid.</summary>
        public const uint BadDeadbandFilterInvalid = 0x808E0000u;
        /// <summary>Communication to the data source has failed. The variable value is the last value that had a good quality.</summary>
        public const uint UncertainNoCommunicationLastUsableValue = 0x408F0000u;
        /// <summary>Whatever was updating this value has stopped doing so.</summary>
        public const uint UncertainLastUsableValue = 0x40900000u;
        /// <summary>The value is an operational value that was manually overwritten.</summary>
        public const uint UncertainSubstituteValue = 0x40910000u;
        /// <summary>The value is an initial value for a variable that normally receives its value from another variable.</summary>
        public const uint UncertainInitialValue = 0x40920000u;
        /// <summary>The value is at one of the sensor limits.</summary>
        public const uint UncertainSensorNotAccurate = 0x40930000u;
        /// <summary>The value is outside of the range of values defined for this parameter.</summary>
        public const uint UncertainEngineeringUnitsExceeded = 0x40940000u;
        /// <summary>The value is derived from multiple sources and has less than the required number of Good sources.</summary>
        public const uint UncertainSubNormal = 0x40950000u;
        /// <summary>The value has been overridden.</summary>
        public const uint GoodLocalOverride = 0x00960000u;
        /// <summary>This Condition refresh failed, a Condition refresh operation is already in progress.</summary>
        public const uint BadRefreshInProgress = 0x80970000u;
        /// <summary>This condition has already been disabled.</summary>
        public const uint BadConditionAlreadyDisabled = 0x80980000u;
        /// <summary>This condition has already been enabled.</summary>
        public const uint BadConditionAlreadyEnabled = 0x80CC0000u;
        /// <summary>Property not available, this condition is disabled.</summary>
        public const uint BadConditionDisabled = 0x80990000u;
        /// <summary>The specified event id is not recognized.</summary>
        public const uint BadEventIdUnknown = 0x809A0000u;
        /// <summary>The event cannot be acknowledged.</summary>
        public const uint BadEventNotAcknowledgeable = 0x80BB0000u;
        /// <summary>The dialog condition is not active.</summary>
        public const uint BadDialogNotActive = 0x80CD0000u;
        /// <summary>The response is not valid for the dialog.</summary>
        public const uint BadDialogResponseInvalid = 0x80CE0000u;
        /// <summary>The condition branch has already been acknowledged.</summary>
        public const uint BadConditionBranchAlreadyAcked = 0x80CF0000u;
        /// <summary>The condition branch has already been confirmed.</summary>
        public const uint BadConditionBranchAlreadyConfirmed = 0x80D00000u;
        /// <summary>The condition has already been shelved.</summary>
        public const uint BadConditionAlreadyShelved = 0x80D10000u;
        /// <summary>The condition is not currently shelved.</summary>
        public const uint BadConditionNotShelved = 0x80D20000u;
        /// <summary>The shelving time not within an acceptable range.</summary>
        public const uint BadShelvingTimeOutOfRange = 0x80D30000u;
        /// <summary>No data exists for the requested time range or event filter.</summary>
        public const uint BadNoData = 0x809B0000u;
        /// <summary>No data found to provide upper or lower bound value.</summary>
        public const uint BadBoundNotFound = 0x80D70000u;
        /// <summary>The server cannot retrieve a bound for the variable.</summary>
        public const uint BadBoundNotSupported = 0x80D80000u;
        /// <summary>Data is missing due to collection started/stopped/lost.</summary>
        public const uint BadDataLost = 0x809D0000u;
        /// <summary>Expected data is unavailable for the requested time range due to an un-mounted volume, an off-line archive or tape, or similar reason for temporary unavailability.</summary>
        public const uint BadDataUnavailable = 0x809E0000u;
        /// <summary>The data or event was not successfully inserted because a matching entry exists.</summary>
        public const uint BadEntryExists = 0x809F0000u;
        /// <summary>The data or event was not successfully updated because no matching entry exists.</summary>
        public const uint BadNoEntryExists = 0x80A00000u;
        /// <summary>The client requested history using a timestamp format the server does not support (i.e requested ServerTimestamp when server only supports SourceTimestamp).</summary>
        public const uint BadTimestampNotSupported = 0x80A10000u;
        /// <summary>The data or event was successfully inserted into the historical database.</summary>
        public const uint GoodEntryInserted = 0x00A20000u;
        /// <summary>The data or event field was successfully replaced in the historical database.</summary>
        public const uint GoodEntryReplaced = 0x00A30000u;
        /// <summary>The value is derived from multiple values and has less than the required number of Good values.</summary>
        public const uint UncertainDataSubNormal = 0x40A40000u;
        /// <summary>No data exists for the requested time range or event filter.</summary>
        public const uint GoodNoData = 0x00A50000u;
        /// <summary>The data or event field was successfully replaced in the historical database.</summary>
        public const uint GoodMoreData = 0x00A60000u;
        /// <summary>The requested number of Aggregates does not match the requested number of NodeIds.</summary>
        public const uint BadAggregateListMismatch = 0x80D40000u;
        /// <summary>The requested Aggregate is not support by the server.</summary>
        public const uint BadAggregateNotSupported = 0x80D50000u;
        /// <summary>The aggregate value could not be derived due to invalid data inputs.</summary>
        public const uint BadAggregateInvalidInputs = 0x80D60000u;
        /// <summary>The aggregate configuration is not valid for specified node.</summary>
        public const uint BadAggregateConfigurationRejected = 0x80DA0000u;
        /// <summary>The request specifies fields which are not valid for the EventType or cannot be saved by the historian.</summary>
        public const uint GoodDataIgnored = 0x00D90000u;
        /// <summary>The request was rejected by the server because it did not meet the criteria set by the server.</summary>
        public const uint BadRequestNotAllowed = 0x80E40000u;
        /// <summary>The request has not been processed by the server yet.</summary>
        public const uint BadRequestNotComplete = 0x81130000u;
        /// <summary>The value does not come from the real source and has been edited by the server.</summary>
        public const uint GoodEdited = 0x00DC0000u;
        /// <summary>There was an error in execution of these post-actions.</summary>
        public const uint GoodPostActionFailed = 0x00DD0000u;
        /// <summary>The related EngineeringUnit has been changed but the Variable Value is still provided based on the previous unit.</summary>
        public const uint UncertainDominantValueChanged = 0x40DE0000u;
        /// <summary>A dependent value has been changed but the change has not been applied to the device.</summary>
        public const uint GoodDependentValueChanged = 0x00E00000u;
        /// <summary>The related EngineeringUnit has been changed but this change has not been applied to the device. The Variable Value is still dependent on the previous unit but its status is currently Bad.</summary>
        public const uint BadDominantValueChanged = 0x80E10000u;
        /// <summary>A dependent value has been changed but the change has not been applied to the device. The quality of the dominant variable is uncertain.</summary>
        public const uint UncertainDependentValueChanged = 0x40E20000u;
        /// <summary>A dependent value has been changed but the change has not been applied to the device. The quality of the dominant variable is Bad.</summary>
        public const uint BadDependentValueChanged = 0x80E30000u;
        /// <summary>The communication layer has raised an event.</summary>
        public const uint GoodCommunicationEvent = 0x00A70000u;
        /// <summary>The system is shutting down.</summary>
        public const uint GoodShutdownEvent = 0x00A80000u;
        /// <summary>The operation is not finished and needs to be called again.</summary>
        public const uint GoodCallAgain = 0x00A90000u;
        /// <summary>A non-critical timeout occurred.</summary>
        public const uint GoodNonCriticalTimeout = 0x00AA0000u;
        /// <summary>One or more arguments are invalid.</summary>
        public const uint BadInvalidArgument = 0x80AB0000u;
        /// <summary>Could not establish a network connection to remote server.</summary>
        public const uint BadConnectionRejected = 0x80AC0000u;
        /// <summary>The server has disconnected from the client.</summary>
        public const uint BadDisconnect = 0x80AD0000u;
        /// <summary>The network connection has been closed.</summary>
        public const uint BadConnectionClosed = 0x80AE0000u;
        /// <summary>The operation cannot be completed because the object is closed, uninitialized or in some other invalid state.</summary>
        public const uint BadInvalidState = 0x80AF0000u;
        /// <summary>Cannot move beyond end of the stream.</summary>
        public const uint BadEndOfStream = 0x80B00000u;
        /// <summary>No data is currently available for reading from a non-blocking stream.</summary>
        public const uint BadNoDataAvailable = 0x80B10000u;
        /// <summary>The asynchronous operation is waiting for a response.</summary>
        public const uint BadWaitingForResponse = 0x80B20000u;
        /// <summary>The asynchronous operation was abandoned by the caller.</summary>
        public const uint BadOperationAbandoned = 0x80B30000u;
        /// <summary>The stream did not return all data requested (possibly because it is a non-blocking stream).</summary>
        public const uint BadExpectedStreamToBlock = 0x80B40000u;
        /// <summary>Non blocking behaviour is required and the operation would block.</summary>
        public const uint BadWouldBlock = 0x80B50000u;
        /// <summary>A value had an invalid syntax.</summary>
        public const uint BadSyntaxError = 0x80B60000u;
        /// <summary>The operation could not be finished because all available connections are in use.</summary>
        public const uint BadMaxConnectionsReached = 0x80B70000u;

        public static string GetDefaultMessage(uint statusCode)
        {
            string value;
            if (DefaultMessages.TryGetValue(statusCode & 0xFFFF0000, out value))
            {
                return value;
            }
            return "An unexpected error occurred.";
        }

        static Dictionary<uint, string> DefaultMessages = new Dictionary<uint, string>()
        {
            [0x00000000]="The result was successful.",
            [0x80010000]="An unexpected error occurred.",
            [0x80020000]="An internal error occurred as a result of a programming or configuration error.",
            [0x80030000]="Not enough memory to complete the operation.",
            [0x80040000]="An operating system resource is not available.",
            [0x80050000]="A low level communication error occurred.",
            [0x80060000]="Encoding halted because of invalid data in the objects being serialized.",
            [0x80070000]="Decoding halted because of invalid data in the stream.",
            [0x80080000]="The message encoding/decoding limits imposed by the stack have been exceeded.",
            [0x80B80000]="The request message size exceeds limits set by the server.",
            [0x80B90000]="The response message size exceeds limits set by the client.",
            [0x80090000]="An unrecognized response was received from the server.",
            [0x800A0000]="The operation timed out.",
            [0x800B0000]="The server does not support the requested service.",
            [0x800C0000]="The operation was cancelled because the application is shutting down.",
            [0x800D0000]="The operation could not complete because the client is not connected to the server.",
            [0x800E0000]="The server has stopped and cannot process any requests.",
            [0x800F0000]="There was nothing to do because the client passed a list of operations with no elements.",
            [0x80100000]="The request could not be processed because it specified too many operations.",
            [0x80DB0000]="The request could not be processed because there are too many monitored items in the subscription.",
            [0x80110000]="The extension object cannot be (de)serialized because the data type id is not recognized.",
            [0x80120000]="The certificate provided as a parameter is not valid.",
            [0x80130000]="An error occurred verifying security.",
            [0x81140000]="The certificate does not meet the requirements of the security policy.",
            [0x80140000]="The certificate has expired or is not yet valid.",
            [0x80150000]="An issuer certificate has expired or is not yet valid.",
            [0x80160000]="The HostName used to connect to a server does not match a HostName in the certificate.",
            [0x80170000]="The URI specified in the ApplicationDescription does not match the URI in the certificate.",
            [0x80180000]="The certificate may not be used for the requested operation.",
            [0x80190000]="The issuer certificate may not be used for the requested operation.",
            [0x801A0000]="The certificate is not trusted.",
            [0x801B0000]="It was not possible to determine if the certificate has been revoked.",
            [0x801C0000]="It was not possible to determine if the issuer certificate has been revoked.",
            [0x801D0000]="The certificate has been revoked.",
            [0x801E0000]="The issuer certificate has been revoked.",
            [0x810D0000]="The certificate chain is incomplete.",
            [0x801F0000]="User does not have permission to perform the requested operation.",
            [0x80200000]="The user identity token is not valid.",
            [0x80210000]="The user identity token is valid but the server has rejected it.",
            [0x80220000]="The specified secure channel is no longer valid.",
            [0x80230000]="The timestamp is outside the range allowed by the server.",
            [0x80240000]="The nonce does appear to be not a random value or it is not the correct length.",
            [0x80250000]="The session id is not valid.",
            [0x80260000]="The session was closed by the client.",
            [0x80270000]="The session cannot be used because ActivateSession has not been called.",
            [0x80280000]="The subscription id is not valid.",
            [0x802A0000]="The header for the request is missing or invalid.",
            [0x802B0000]="The timestamps to return parameter is invalid.",
            [0x802C0000]="The request was cancelled by the client.",
            [0x80E50000]="Too many arguments were provided.",
            [0x810E0000]="The server requires a license to operate in general or to perform a service or operation, but existing license is expired.",
            [0x810F0000]="The server has limits on number of allowed operations / objects, based on installed licenses, and these limits where exceeded.",
            [0x81100000]="The server does not have a license which is required to operate in general or to perform a service or operation.",
            [0x002D0000]="The subscription was transferred to another session.",
            [0x002E0000]="The processing will complete asynchronously.",
            [0x002F0000]="Sampling has slowed down due to resource limitations.",
            [0x00300000]="The value written was accepted but was clamped.",
            [0x80310000]="Communication with the data source is defined, but not established, and there is no last known value available.",
            [0x80320000]="Waiting for the server to obtain values from the underlying data source.",
            [0x80330000]="The syntax of the node id is not valid.",
            [0x80340000]="The node id refers to a node that does not exist in the server address space.",
            [0x80350000]="The attribute is not supported for the specified Node.",
            [0x80360000]="The syntax of the index range parameter is invalid.",
            [0x80370000]="No data exists within the range of indexes specified.",
            [0x80380000]="The data encoding is invalid.",
            [0x80390000]="The server does not support the requested data encoding for the node.",
            [0x803A0000]="The access level does not allow reading or subscribing to the Node.",
            [0x803B0000]="The access level does not allow writing to the Node.",
            [0x803C0000]="The value was out of range.",
            [0x803D0000]="The requested operation is not supported.",
            [0x803E0000]="A requested item was not found or a search operation ended without success.",
            [0x803F0000]="The object cannot be used because it has been deleted.",
            [0x80400000]="Requested operation is not implemented.",
            [0x80410000]="The monitoring mode is invalid.",
            [0x80420000]="The monitoring item id does not refer to a valid monitored item.",
            [0x80430000]="The monitored item filter parameter is not valid.",
            [0x80440000]="The server does not support the requested monitored item filter.",
            [0x80450000]="A monitoring filter cannot be used in combination with the attribute specified.",
            [0x80460000]="A mandatory structured parameter was missing or null.",
            [0x80470000]="The event filter is not valid.",
            [0x80480000]="The content filter is not valid.",
            [0x80C10000]="An unrecognized operator was provided in a filter.",
            [0x80C20000]="A valid operator was provided, but the server does not provide support for this filter operator.",
            [0x80C30000]="The number of operands provided for the filter operator was less then expected for the operand provided.",
            [0x80490000]="The operand used in a content filter is not valid.",
            [0x80C40000]="The referenced element is not a valid element in the content filter.",
            [0x80C50000]="The referenced literal is not a valid value.",
            [0x804A0000]="The continuation point provide is longer valid.",
            [0x804B0000]="The operation could not be processed because all continuation points have been allocated.",
            [0x804C0000]="The reference type id does not refer to a valid reference type node.",
            [0x804D0000]="The browse direction is not valid.",
            [0x804E0000]="The node is not part of the view.",
            [0x81120000]="The number was not accepted because of a numeric overflow.",
            [0x804F0000]="The ServerUri is not a valid URI.",
            [0x80500000]="No ServerName was specified.",
            [0x80510000]="No DiscoveryUrl was specified.",
            [0x80520000]="The semaphore file specified by the client is not valid.",
            [0x80530000]="The security token request type is not valid.",
            [0x80540000]="The security mode does not meet the requirements set by the server.",
            [0x80550000]="The security policy does not meet the requirements set by the server.",
            [0x80560000]="The server has reached its maximum number of sessions.",
            [0x80570000]="The user token signature is missing or invalid.",
            [0x80580000]="The signature generated with the client certificate is missing or invalid.",
            [0x80590000]="The client did not provide at least one software certificate that is valid and meets the profile requirements for the server.",
            [0x80C60000]="The server does not support changing the user identity assigned to the session.",
            [0x805A0000]="The request was cancelled by the client with the Cancel service.",
            [0x805B0000]="The parent node id does not to refer to a valid node.",
            [0x805C0000]="The reference could not be created because it violates constraints imposed by the data model.",
            [0x805D0000]="The requested node id was reject because it was either invalid or server does not allow node ids to be specified by the client.",
            [0x805E0000]="The requested node id is already used by another node.",
            [0x805F0000]="The node class is not valid.",
            [0x80600000]="The browse name is invalid.",
            [0x80610000]="The browse name is not unique among nodes that share the same relationship with the parent.",
            [0x80620000]="The node attributes are not valid for the node class.",
            [0x80630000]="The type definition node id does not reference an appropriate type node.",
            [0x80640000]="The source node id does not reference a valid node.",
            [0x80650000]="The target node id does not reference a valid node.",
            [0x80660000]="The reference type between the nodes is already defined.",
            [0x80670000]="The server does not allow this type of self reference on this node.",
            [0x80680000]="The reference type is not valid for a reference to a remote server.",
            [0x80690000]="The server will not allow the node to be deleted.",
            [0x40BC0000]="The server was not able to delete all target references.",
            [0x806A0000]="The server index is not valid.",
            [0x806B0000]="The view id does not refer to a valid view node.",
            [0x80C90000]="The view timestamp is not available or not supported.",
            [0x80CA0000]="The view parameters are not consistent with each other.",
            [0x80CB0000]="The view version is not available or not supported.",
            [0x40C00000]="The list of references may not be complete because the underlying system is not available.",
            [0x00BA0000]="The server should have followed a reference to a node in a remote server but did not. The result set may be incomplete.",
            [0x80C80000]="The provided Nodeid was not a type definition nodeid.",
            [0x406C0000]="One of the references to follow in the relative path references to a node in the address space in another server.",
            [0x806D0000]="The requested operation has too many matches to return.",
            [0x806E0000]="The requested operation requires too many resources in the server.",
            [0x806F0000]="The requested operation has no match to return.",
            [0x80700000]="The max age parameter is invalid.",
            [0x80E60000]="The operation is not permitted over the current secure channel.",
            [0x80710000]="The history details parameter is not valid.",
            [0x80720000]="The server does not support the requested operation.",
            [0x80BD0000]="The defined timestamp to return was invalid.",
            [0x80730000]="The server does not support writing the combination of value, status and timestamps provided.",
            [0x80740000]="The value supplied for the attribute is not of the same type as the attribute's value.",
            [0x80750000]="The method id does not refer to a method for the specified object.",
            [0x80760000]="The client did not specify all of the input arguments for the method.",
            [0x81110000]="The executable attribute does not allow the execution of the method.",
            [0x80770000]="The server has reached its maximum number of subscriptions.",
            [0x80780000]="The server has reached the maximum number of queued publish requests.",
            [0x80790000]="There is no subscription available for this session.",
            [0x807A0000]="The sequence number is unknown to the server.",
            [0x807B0000]="The requested notification message is no longer available.",
            [0x807C0000]="The client of the current session does not support one or more Profiles that are necessary for the subscription.",
            [0x80BF0000]="The sub-state machine is not currently active.",
            [0x81150000]="An equivalent rule already exists.",
            [0x807D0000]="The server cannot process the request because it is too busy.",
            [0x807E0000]="The type of the message specified in the header invalid.",
            [0x807F0000]="The SecureChannelId and/or TokenId are not currently in use.",
            [0x80800000]="The size of the message specified in the header is too large.",
            [0x80810000]="There are not enough resources to process the request.",
            [0x80820000]="An internal error occurred.",
            [0x80830000]="The server does not recognize the QueryString specified.",
            [0x80840000]="The request could not be sent because of a network interruption.",
            [0x80850000]="Timeout occurred while processing the request.",
            [0x80860000]="The secure channel has been closed.",
            [0x80870000]="The token has expired or is not recognized.",
            [0x80880000]="The sequence number is not valid.",
            [0x80BE0000]="The applications do not have compatible protocol versions.",
            [0x80890000]="There is a problem with the configuration that affects the usefulness of the value.",
            [0x808A0000]="The variable should receive its value from another variable, but has never been configured to do so.",
            [0x808B0000]="There has been a failure in the device/data source that generates the value that has affected the value.",
            [0x808C0000]="There has been a failure in the sensor from which the value is derived by the device/data source.",
            [0x808D0000]="The source of the data is not operational.",
            [0x808E0000]="The deadband filter is not valid.",
            [0x408F0000]="Communication to the data source has failed. The variable value is the last value that had a good quality.",
            [0x40900000]="Whatever was updating this value has stopped doing so.",
            [0x40910000]="The value is an operational value that was manually overwritten.",
            [0x40920000]="The value is an initial value for a variable that normally receives its value from another variable.",
            [0x40930000]="The value is at one of the sensor limits.",
            [0x40940000]="The value is outside of the range of values defined for this parameter.",
            [0x40950000]="The value is derived from multiple sources and has less than the required number of Good sources.",
            [0x00960000]="The value has been overridden.",
            [0x80970000]="This Condition refresh failed, a Condition refresh operation is already in progress.",
            [0x80980000]="This condition has already been disabled.",
            [0x80CC0000]="This condition has already been enabled.",
            [0x80990000]="Property not available, this condition is disabled.",
            [0x809A0000]="The specified event id is not recognized.",
            [0x80BB0000]="The event cannot be acknowledged.",
            [0x80CD0000]="The dialog condition is not active.",
            [0x80CE0000]="The response is not valid for the dialog.",
            [0x80CF0000]="The condition branch has already been acknowledged.",
            [0x80D00000]="The condition branch has already been confirmed.",
            [0x80D10000]="The condition has already been shelved.",
            [0x80D20000]="The condition is not currently shelved.",
            [0x80D30000]="The shelving time not within an acceptable range.",
            [0x809B0000]="No data exists for the requested time range or event filter.",
            [0x80D70000]="No data found to provide upper or lower bound value.",
            [0x80D80000]="The server cannot retrieve a bound for the variable.",
            [0x809D0000]="Data is missing due to collection started/stopped/lost.",
            [0x809E0000]="Expected data is unavailable for the requested time range due to an un-mounted volume, an off-line archive or tape, or similar reason for temporary unavailability.",
            [0x809F0000]="The data or event was not successfully inserted because a matching entry exists.",
            [0x80A00000]="The data or event was not successfully updated because no matching entry exists.",
            [0x80A10000]="The client requested history using a timestamp format the server does not support (i.e requested ServerTimestamp when server only supports SourceTimestamp).",
            [0x00A20000]="The data or event was successfully inserted into the historical database.",
            [0x00A30000]="The data or event field was successfully replaced in the historical database.",
            [0x40A40000]="The value is derived from multiple values and has less than the required number of Good values.",
            [0x00A50000]="No data exists for the requested time range or event filter.",
            [0x00A60000]="The data or event field was successfully replaced in the historical database.",
            [0x80D40000]="The requested number of Aggregates does not match the requested number of NodeIds.",
            [0x80D50000]="The requested Aggregate is not support by the server.",
            [0x80D60000]="The aggregate value could not be derived due to invalid data inputs.",
            [0x80DA0000]="The aggregate configuration is not valid for specified node.",
            [0x00D90000]="The request specifies fields which are not valid for the EventType or cannot be saved by the historian.",
            [0x80E40000]="The request was rejected by the server because it did not meet the criteria set by the server.",
            [0x81130000]="The request has not been processed by the server yet.",
            [0x00DC0000]="The value does not come from the real source and has been edited by the server.",
            [0x00DD0000]="There was an error in execution of these post-actions.",
            [0x40DE0000]="The related EngineeringUnit has been changed but the Variable Value is still provided based on the previous unit.",
            [0x00E00000]="A dependent value has been changed but the change has not been applied to the device.",
            [0x80E10000]="The related EngineeringUnit has been changed but this change has not been applied to the device. The Variable Value is still dependent on the previous unit but its status is currently Bad.",
            [0x40E20000]="A dependent value has been changed but the change has not been applied to the device. The quality of the dominant variable is uncertain.",
            [0x80E30000]="A dependent value has been changed but the change has not been applied to the device. The quality of the dominant variable is Bad.",
            [0x00A70000]="The communication layer has raised an event.",
            [0x00A80000]="The system is shutting down.",
            [0x00A90000]="The operation is not finished and needs to be called again.",
            [0x00AA0000]="A non-critical timeout occurred.",
            [0x80AB0000]="One or more arguments are invalid.",
            [0x80AC0000]="Could not establish a network connection to remote server.",
            [0x80AD0000]="The server has disconnected from the client.",
            [0x80AE0000]="The network connection has been closed.",
            [0x80AF0000]="The operation cannot be completed because the object is closed, uninitialized or in some other invalid state.",
            [0x80B00000]="Cannot move beyond end of the stream.",
            [0x80B10000]="No data is currently available for reading from a non-blocking stream.",
            [0x80B20000]="The asynchronous operation is waiting for a response.",
            [0x80B30000]="The asynchronous operation was abandoned by the caller.",
            [0x80B40000]="The stream did not return all data requested (possibly because it is a non-blocking stream).",
            [0x80B50000]="Non blocking behaviour is required and the operation would block.",
            [0x80B60000]="A value had an invalid syntax.",
            [0x80B70000]="The operation could not be finished because all available connections are in use.",
        };

    }
}
